name: limelightphotography
favicon: null
layout_spectrum: 0.13153063878417015
typography_spectrum: 0.44420413253828883
cta:
  domain: null
  bucket: null
  version: null
analytics:
  google: null
  facebook: null
  twitter: null
opengraph:
  image: null
  type: null
  appId: null
color:
  brandColors:
    - '#9D2D3C'
    - '#DDE4DD'
    - '#BCAB47'
    - '#6B574B'
    - '#160600'
  brandStrength: 0.8778449662495404
  lightness: 0.8600849315989763
  saturation: 0.43003544863313437
  rhythmicContrast: 0.05362516362220049
purpose: []
