name: Limelight Photography
favicon: null
layout_spectrum: 0.25376
typography_spectrum: 0.42584
title: Limelight Photography
cta:
  domain: null
  bucket: null
  version: null
analytics:
  google: null
  facebook: null
  twitter: null
opengraph:
  image: null
  type: null
  appId: null
color:
  brandColors:
    - '#ffffff'
    - '#b6c510'
    - '#ededb1'
    - '#000000'
    - '#868664'
  brandStrength: 1
  lightness: 0.5
  saturation: 0.5
  rhythmicContrast: 0
purpose: []
